#port설정
server:
  port: 9000
  
#mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-g92gp-kr.vpc-pub-cdb.ntruss.com:3306/together?serverTimezone=Asia/Seoul
    username: together
    password: together123!@#
  servlet:
    multipart:
      max-file-size:
        20MB
        
#email
  mail:
  # host, port는 naver에서 정해준 값
    host: smtp.naver.com
    port: 465
    # 본인 naver 계정 정보 삽입
    username: together2jo@naver.com
    password: qlxmzoavm701!@
    protocol: smtp
    # 전송하기 위한 prop으로 ssl의 신뢰, 권한 등 사용허가
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
    
#mybatis
mybatis:
  type-aliases-package: com.semi.dto
  mapper-locations:
  - /mapper/**/*.xml
